Stretch goal copy
seungyonkim/aws-toolkit-vscode pull request #6
Opened 2021-08-03 17:23 UTC by seungyonkim

## Problem
In my previous pull request https://github.com/seungyonkim/aws-toolkit-vscode/pull/5, I have added the functionality that  visualizes state machine resources defined using the AWS CDK from within VSCode. In AWS Toolkit for VSCode extension, feature parity for most commands is supported through the VSCode command palette. 

## Solution
The changes enhance the user experience by achieving visualization feature parity in the AWS Toolkit for VSCode between state machines defined in ASL and state machines defined using the AWS CDK.

## Description of Changes
```diff
-This is the first draft of code and is subject to change. More unit tests will be added shortly. 
```
- `previewStateMachineCDKWizard.ts` helps users choose the workspace, cdk application, and state machine that they want to visualize. 
- `renderGraphCommandPalette.ts` passes the answers collected from the user by the wizard and passes it to the `renderGraphCommand.ts` command.

## Changes to be Added 
- Unit tests for `previewStateMachineCDKWizard`

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-11 00:46 UTC, seungyonkim commented on src/test/stepFunctions/commands/getStateMachineDefinitionFromCfnTemplate.test.ts
> +//const escapedJsonString: string = `{\"StartAt\":\"Submit Job\",\"States\":{\"Submit Job\":{\"Next\":\"Wait X Seconds\",\"Type\":\"Task\",\"Resource\":\"",{"Ref":"SubmitJobFB773A16"},"\",\"ResultPat
This escaped string automatically gets unescaped when running tests, would there be a way to keep the string as escaped?

2021-08-11 00:47 UTC, seungyonkim commented on src/test/cdk/explorer/commands/visualizeStateMachineCDK.test.ts
> +    it('Test AslVisualizationCDKManager managedVisualizationsCDK set removes visualization on removal of template.json file, single visCDK', async function () {
Not sure if I need to (if yes, how to) test the last three cases. Implementation is left blank.

2021-08-11 00:48 UTC, seungyonkim commented on src/cdk/commands/aslVisualizationCDK.ts
>      protected makeWebviewTitle(sourceDocumentUri: vscode.Uri): string {
Need to fix this so it shows name of state machine instead of 'undefined'

2021-08-12 10:24 UTC, jormello requested changes

2021-08-12 10:24 UTC, jormello commented on src/cdk/commands/aslVisualizationCDK.ts
>          this.uniqueIdentifier = uniqueIdentifier
The uniqueIdentifier already contains the stateMachineName. Can we refactor to store the app name, which can be combined with the stateMachineName to create the uniqueIdentifier.

2021-08-12 10:24 UTC, jormello commented on src/cdk/commands/aslVisualizationCDKManager.ts
> +export function getCDKAppWorkspaceName(cdkOutPath: string) {
Does this need to be exported? Seems like it's only being used in this file.

2021-08-12 10:24 UTC, jormello commented on src/stepFunctions/commands/visualizeStateMachine/getStateMachineDefinitionFromCfnTemplate.ts
> +        let key = ''
Can just declare without assigning to a value. 

`let key`

2021-08-12 10:24 UTC, jormello commented on src/stepFunctions/commands/visualizeStateMachine/getStateMachineDefinitionFromCfnTemplate.ts
> +            key = matchingKeyList.pop()!
Since we know the list is of length 1, we can directly index the element with `matchingKeyList[0]`.

2021-08-12 10:24 UTC, jormello commented on src/stepFunctions/commands/visualizeStateMachine/getStateMachineDefinitionFromCfnTemplate.ts
> +            //return minimun length key in matchingKeyList
Nit: typo minimum

2021-08-12 10:24 UTC, jormello commented on src/stepFunctions/commands/visualizeStateMachine/getStateMachineDefinitionFromCfnTemplate.ts
> +        return data
Can simplify to just `return JSON.stringify(definitionString)`

2021-08-12 10:24 UTC, jormello commented on src/stepFunctions/commands/visualizeStateMachine/getStateMachineDefinitionFromCfnTemplate.ts
>      if (typeof (escapedAslJsonStr) != "string") return escapedAslJsonStr;
We should be safe to remove the type check since the parameter is typed.

2021-08-12 10:24 UTC, jormello commented on src/stepFunctions/commands/visualizeStateMachine/getStateMachineDefinitionFromCfnTemplate.ts
>      if (typeof (escapedAslJsonStr) != "string") return escapedAslJsonStr;
Got what looks to be a working version with the following simplified code where we don't need to stringify the definitionString before passing it to be converted to ASL:

```
interface CdkStateMachineWithPlaceholders {
    "Fn::Join": (string | any)[]
}

/**
 * @param {string} escapedAslJsonStr - json state machine construct definition
 * @returns unescaped json state machine construct definition in asl.json
 */
export function toUnescapedAslJsonString(escapedAslJsonStr: string | CdkStateMachineWithPlaceholders) {
    if (typeof(escapedAslJsonStr) === 'string') {
        return escapedAslJsonStr
    }

    const definitionStringWithPlaceholders: (string | any)[] = escapedAslJsonStr['Fn::Join'][1]
    const definitionStringSegments: string[] = definitionStringWithPlaceholders.filter((segment) => typeof(segment) === 'string')

    return definitionStringSegments.join('')
}
```

2021-08-12 10:24 UTC, jormello commented on src/cdk/commands/aslVisualizationCDKManager.ts
>          const uniqueIdentifier = node.label
Might be good to rename this to stateMachineName

2021-08-12 10:24 UTC, jormello commented on src/cdk/wizards/previewStateMachineCDKWizard.ts
> +export function getCDKAppWorkspaceName(cdkJsonPath: string) {
Is this code duplicated from `src/cdk/commands/aslVisualizationCDKManager.ts`?

2021-08-12 10:24 UTC, jormello commented on src/cdk/wizards/previewStateMachineCDKWizard.ts
> +    cdkApplocation: CdkAppLocation | undefined
Nit: typo Applocation

2021-08-12 10:24 UTC, jormello commented on src/cdk/wizards/previewStateMachineCDKWizard.ts
>          cdkAppLocations.map(obj => {
The map function transforms each element, and returns the resulting transformed array. You can replace this with:

```
const CDK_APPLOCATIONS: CdkAppLocationPickItem[] = cdkAppLocations.map(obj => {
            return {
                label: getCDKAppWorkspaceName(obj.cdkJsonPath),
                cdkApplocation: obj
            }
        })
```

2021-08-12 10:24 UTC, jormello commented on src/cdk/wizards/previewStateMachineCDKWizard.ts
> +        const TOP_LEVEL_NODES: TopLevelNodePickItem[] = []
Can keep the variable name in lowercase. Similar comment about assigning as the result of the map function. Can also rename the variable to something more descriptive.

2021-08-12 10:24 UTC, jormello commented on src/cdk/wizards/previewStateMachineCDKWizard.ts
> +                label: node.label ? node.label : '',
Can replace instances where we want a default if undefined like this with logical OR.

```
node.label || ''
```

2021-08-12 10:24 UTC, jormello commented on src/cdk/wizards/previewStateMachineCDKWizard.ts
>          const appNode = new AppNode(appLocation!)
Don't think you need the `!`

2021-08-12 10:24 UTC, jormello commented on src/cdk/wizards/previewStateMachineCDKWizard.ts
> +                if (node.contextValue === 'awsCdkStateMachineNode') {
Can use a filter chained to a map state to first filter out all nodes that aren't state machine nodes, then map each of the state machine nodes into PickItem object format.

2021-08-12 19:00 UTC, jormello requested changes

2021-08-12 19:00 UTC, jormello commented on src/cdk/activation.ts
> +import { renderStateMachineGraphCommand } from './commands/ renderStateMachineGraph'
Nit: extra space.

2021-08-12 19:00 UTC, jormello commented on src/cdk/commands/aslVisualizationCDK.ts
> +    // protected makeWebviewTitle(sourceDocumentUri: vscode.Uri): string {
When we cut the PR, let's explicitly call out that we need to fix this bug

2021-08-12 19:00 UTC, jormello commented on src/cdk/wizards/previewStateMachineCDKWizard.ts
> +            topLevelNodes.filter( function (node) {
Nit: extra space before `function`

2021-08-12 22:58 UTC, jormello approved these changes

2021-08-12 23:21 UTC, merged